### ISSUE TITLE
Generation of valid tests for unsupported VLEN target  

### ISSUE THREAD

**Issue by quswar-abid** [hushenwei2000/rvv-atg#12]
It is documented in the README that the generator supports [VLEN up to 1024](https://github.com/hushenwei2000/rvv-atg/#:~:text=128%20~%202%5E16-,128%20~%201024,-Spike%20now%20support). However it is observed that the test generator can generate tests up to VLEN of 8192. Running the following command gives generated tests.

```
python3 run.py -t i -i vadd --vlen 8192 --vsew 64 --lmul 1
```

Even `python3 run.py -t i -i vadd --vlen 4096 --vsew 64 --lmul 1` and `python3 run.py -t i -i vadd --vlen 2048 --vsew 64 --lmul 1` works as well. I even ran the tests with `VLEN == 4096` on an RTL as well. It did not create tests for `VLEN == 16384` though.

THE questions I want to ask is .. **does the README need to be updated?** or **is there any problem that I haven't noticed?**

**Comment by hushenwei2000** [comment]
VLEN has little impact on our generator, so a larger VLEN should be able to generate successfully (we think). However, we only tested the maximum VLEN=4096, so we **can't guarantee** the success of larger VLEN.

**Comment by quswar-abid** [comment]
That's great. I'll close the issue now.
